apiVersion: apps/v1 
kind: Deployment
metadata: 
 name: depoyment-1
 labels: 
  author: intelliq
spec: 
 replicas: 4
 selector: 
  matchLabels: 
   author: intelliq
 template: 
  metadata: 
   name: d1_pod
   labels: 
    author: intelliq
  spec: 
   containers: 
    - name: nginx
      image: nginx:1.7.9
      ports: 
       - containerPort: 80
         hostPort : 9090

