apiVersion: v1
kind: Pod
metadata: 
 name: jenkins-pod
 labels: 
  author: intelliq
spec: 
 containers: 
  - name: jenkinsserver
    image: jenkins
    ports: 
     - containerPort: 8080
       hostPort: 8080
