apiVersion: v1
kind: Pod
metadata: 
 name: j1-pod
 labels: 
  author: intelliq
  type: j1
spec:
 containers: 
  - name: jenkins
    image: jenkins
    ports:
     - containerPort: 8080
       hostPort: 8080
    
