---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels: 
   author: intelliqit
   type: mydatabase
spec: 
 containers: 
  - image: postgres
    name: mydb
    env:
     - name: POSTGRES_PASSWORD
       value: mypassword
...
