---
apiVersion: v1
kind: Pod
metadata: 
 name: nginx-pod
 labels:
        author: intelliqit
        crdate: feb21
spec:
        containers: 
                - name: webserver
                  image: nginx
...
