---
apiVersion: v1
kind: Pod
metadata: 
 name: postgress-pod
 labels: 
  author: intelliq
  type: database
spec: 
 containers:
  - image: postgres
    name: mydb
    env: 
      - name: POSTGRES_PASSWORD
        value: myintelliqit
      - name: POSTGRES_USER
        value: mydbuser
...
