---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: replicaset1
 labels: 
  author: intelliq
spec: 
 replicas: 2 
 selector: 
  matchLabels: 
   author: intelliq
 template: 
  metadata: 
   name: http-pod
   labels: 
    author: intelliq
  spec: 
   containers: 
    - name: myhttpd
      image: httpd
      ports: 
       - containerPort: 80
         hostPort: 8080


